name: Upload website affordable

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@master


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      
      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      
      - name: Deploy to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --include 'build/**/*' --exclude '*'
          source: build/
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

